export const ERR_UNAUTHORIZED = 403,
  ERR_NOT_FOUND = 404,
  ERR_INVALID_ID = 500,
  ERR_TOO_EARLY = 501,
  ERR_LISTING = 502,
  ERR_WRONG_COMMISSION = 503,
  ERR_ALREADY_DONE = 505,
  ERR_NOT_LAUNCHED = 506,
  ERR_MAX_LIMIT_REACHED = 507,
  ERR_FATALE = 999;

export const ERR_SAME_SENDER_RECIPIENT = 2,
  ERR_NO_SUCH_ASSET_ = 3;
