[project]
name = 'backend-stacks'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C.commission-trait'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[contracts.commission-free]
path = 'contracts/external/commission-free.clar'
clarity_version = 1

[contracts.ryder-mint-free]
path = 'contracts/external/ryder-mint-free.clar'
clarity_version = 1

[contracts.ryder-mint-helper-10]
path = 'contracts/external/ryder-mint-helper-10.clar'
clarity_version = 1

[contracts.ryder-mint]
path = 'contracts/ryder-mint.clar'
clarity_version = 1

[contracts.ryder-nft]
path = 'contracts/ryder-nft.clar'
clarity_version = 1

[contracts.ryder-nft-allow-list]
path = 'contracts/ryder-nft-allow-list.clar'
clarity_version = 1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
