[project]
name = "backend-stacks"
authors = []
description = ""
telemetry = true
cache_dir = "/home/friedger/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id="SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C.commission-trait"

[[project.requirements]]
contract_id="SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait" 

[contracts.commission-free]
path = "contracts/external/commission-free.clar"
depends_on = []

[contracts.ryder-bridge]
path = "contracts/ryder-bridge.clar"
depends_on = ["ryder-nft"]


[contracts.ryder-mint]
path = "contracts/ryder-mint.clar"
depends_on = ["ryder-nft"]

[contracts.ryder-nft]
path = "contracts/ryder-nft.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
